# Generated by Django 3.1.2 on 2020-12-02 08:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Other', max_length=5)),
                ('gender', models.CharField(default='Prefer Not to Say', max_length=20)),
                ('account_type', models.CharField(default='Huntee', max_length=6)),
                ('profile_picture', models.ImageField(default='default/default.jpg', upload_to='profile_pics')),
                ('resume', models.FileField(default='default/default.pdf', upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume (.pdf only)')),
                ('website', models.URLField(blank=True, default='')),
                ('privacy', models.CharField(default='Public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
