# Generated by Django 3.1.2 on 2020-12-02 05:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Other', max_length=5)),
                ('gender', models.CharField(default='Prefer Not to Say', max_length=20)),
                ('account_type', models.CharField(default='Huntee', max_length=6)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('resume', models.FileField(default='default.pdf', upload_to=users.models.Profile.update_resume_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume (.pdf only)')),
                ('website', models.URLField(blank=True, default='')),
                ('privacy', models.CharField(default='Public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(default='', max_length=150)),
                ('rating', models.CharField(default='1', max_length=1)),
                ('content', models.TextField(default='')),
                ('author', models.OneToOneField(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
