# Generated by Django 3.1.2 on 2020-12-02 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default='Huntee', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Prefer Not to Say', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(default='Public', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='resumes/default.pdf', upload_to='resumes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume (.pdf only)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Other', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(default='', max_length=150)),
                ('rating', models.CharField(default='1', max_length=1)),
                ('content', models.TextField(default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
