# Generated by Django 3.1.2 on 2020-11-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default='Huntee', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Other', max_length=5),
        ),
    ]
