# Generated by Django 3.1.2 on 2020-11-28 09:11

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_samples',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='default.pdf', upload_to=users.models.Profile.update_resume_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
