# Generated by Django 3.1.2 on 2021-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201203_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='XXXX-XX-XX', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_employment',
            field=models.CharField(default='No Employment', max_length=50),
        ),
    ]
