# Generated by Django 3.1.2 on 2020-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201128_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy',
            field=models.CharField(default='Public', max_length=10),
        ),
    ]
