# Generated by Django 3.1.2 on 2020-11-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_privacy'),
        ('users', '0002_auto_20201119_0915'),
    ]

    operations = [
    ]
