# Generated by Django 3.1.2 on 2020-11-30 20:19

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20201128_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='default.pdf', upload_to=users.models.Profile.update_resume_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Resume (.pdf only)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
