# Generated by Django 3.1.2 on 2020-11-30 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
