# Generated by Django 3.1.2 on 2020-12-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='employer',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
