# Generated by Django 3.1.2 on 2020-12-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='employer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
