# Generated by Django 3.1.2 on 2020-12-01 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author',
            field=models.ForeignKey(default='something', on_delete=django.db.models.deletion.CASCADE, related_name='Profile.user+', to=settings.AUTH_USER_MODEL),
        ),
    ]
