# Generated by Django 3.1.2 on 2020-12-03 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='huntee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='huntee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='hunter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hunter', to=settings.AUTH_USER_MODEL),
        ),
    ]
