# Generated by Django 3.1.2 on 2020-12-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201203_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='hunter',
        ),
    ]
