# Generated by Django 3.1.2 on 2020-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listings_hunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='tag1',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11),
        ),
        migrations.AddField(
            model_name='listings',
            name='tag2',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11),
        ),
        migrations.AddField(
            model_name='listings',
            name='tag3',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11),
        ),
    ]
