# Generated by Django 3.1.2 on 2020-12-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201203_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tag1',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11, verbose_name='TAG ONE'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tag2',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11, verbose_name='TAG TWO'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tag3',
            field=models.CharField(choices=[('NONE', 'NONE'), ('AI', 'AI'), ('DEVELOPMENT', 'DEVELOPMENT'), ('DESIGN', 'DESIGN'), ('C++', 'C++'), ('Java', 'Java'), ('Python', 'Python'), ('Web', 'Web')], default='NONE', max_length=11, verbose_name='TAG THREE'),
        ),
    ]
