# Generated by Django 3.1.2 on 2020-12-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listings_hunter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='tag1',
            field=models.CharField(default='NONE', max_length=11, verbose_name='TAG ONE'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tag2',
            field=models.CharField(default='NONE', max_length=11, verbose_name='TAG TWO'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tag3',
            field=models.CharField(default='NONE', max_length=11, verbose_name='TAG THREE'),
        ),
    ]
