# Generated by Django 3.1.2 on 2021-02-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210222_1638'),
        ('listings', '0008_auto_20210222_2123'),
    ]

    operations = [
    ]
