# Generated by Django 3.1.2 on 2021-02-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listings_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='status',
            field=models.CharField(choices=[('Strutting', 'Strutting'), ('Claimed', 'Claimed'), ('Started', 'Started'), ('Milestone 1', 'Milestone 1'), ('Milestone 2', 'Milestone 2'), ('Milestone 3', 'Milestone 3'), ('Complete', 'Complete'), ('Payment Issued', 'Payment Issued')], default='Strutting', max_length=14),
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Strutting', 'Strutting'), ('Claimed', 'Claimed'), ('Started', 'Started'), ('Milestone 1', 'Milestone 1'), ('Milestone 2', 'Milestone 2'), ('Milestone 3', 'Milestone 3'), ('Complete', 'Complete'), ('Payment Issued', 'Payment Issued')], default='Started', max_length=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('listing', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='listings.listings')),
            ],
        ),
    ]
